version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: fashion-shop-db
    restart: unless-stopped
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: fashion_user
      POSTGRES_PASSWORD: fashion_pass
      POSTGRES_DB: fashion_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U fashion_user -d fashion_db']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: fashion-shop-redis
    restart: unless-stopped
    ports:
      - '6381:6379'
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
  redis_data:
